name: Events Demo
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: output events data
      run: echo " ${{ toJson(github.event) }}"
    - name: Get Code
      uses: actions/checkout@v2
