name: Events Demo

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Get Code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependancies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Test Code
      run: npm run test

    - name: Build Code
      run: npm run build

    - name: Deploy Project
      run: echo "Deploying ..."

    - name: output events data
      run: echo " ${{ toJson(github.event) }}"
